# Generated by Django 4.1.2 on 2022-10-30 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contacts', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EquipTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('companies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.company')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users_images')),
                ('tags', models.ManyToManyField(to='items.equiptag')),
            ],
        ),
    ]
